services:
  mysqldb:
    image: mysql:5.7
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_DATABASE: 'hackaton'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    container_name: mysql
    expose:
      - '3306'
    volumes:
      - ./my-db:/var/lib/mysql
    networks:
      - my_network

  hackaton:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: api-hackaton
    links:
      - mysqldb
    networks:
      - my_network

networks:
  my_network:

volumes:
  my-db: